ARG GOLANG_VERSION=1.19.0-alpine3.15
ARG ALPINE_VERSION=3.18

FROM library/golang:${GOLANG_VERSION}-alpine${ALPINE_VERSION}
RUN apk --no-cache add \
    bash \
    coreutils \
    curl \
    docker \
    file \
    g++ \
    gcc \
    git \
    make \
    mercurial \
    rsync \
    subversion \
    wget \
    yq
COPY scripts/ /usr/local/go/bin/
RUN set -x \
    && chmod -v +x /usr/local/go/bin/go-*.sh \
    && go version
