name: Build And Push
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: read

jobs:
  push-multiarch:
    permissions:
      contents: read
      id-token: write
    name: Build and Push amd64 and arm64
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
      REPOSITORY_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: "Read secrets"
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials password | DOCKER_PASSWORD
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Docker Registry Login
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set the GOLANG_VERSION value
        id: get-GOLANG_VERSION
        run: |
          echo "GO_VERSION=$(make go-version)" >> "$GITHUB_ENV"

      - name: Build Container Image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          push: true
          build-args: |
            "GOLANG_VERSION=${{ env.GO_VERSION }}"
          tags: ${{ env.REPOSITORY_OWNER }}/hardened-build-base:${{ env.TAG }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64

